thingsboard:
  host: "nuc10.i.uassist.cn"
  port: 1883
  access_token: "ZJKsK4GqSZTm8vAn3CYg"

device:
  name: "SCREEN-PC-01"
  heartbeat_interval: 10

player:
  slideplayer:
    exe: "D:\\Program Files\\Kingsoft\\WPS Office\\ksolaunch.exe"
  browser:
    exe: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
    exe_args:
      - "--start-fullscreen"
      - "--remote-debugging-port=9222"
      - "--user-data-dir=D:\\Temp\\ChromeDevSession"
      - "--remote-allow-origins=*"
    cdp_port: 9222
  videoplayer:
    exe: "D:\\Program Files\\VideoLAN\\VLC\\vlc.exe"
    host: "127.0.0.1"
    port: 9999
  avatarplayer:
    exe: "D:\\Files\\Documents\\Project\\yancheng_playground\\avatar_player\\dist\\avatar-player 1.0.0.exe"
    host: "127.0.0.1"
    port: 9999